# To use:
# conda env create --file conda_requirements.yml

name: lab10
dependencies:
  - python=3.11.8
  - numpy=1.26.4
  - matplotlib=3.8.0
  - ipykernel=6.28.0
  - ipympl=0.9.3
  - qt=5.15.9
  - pyqt=5.15.10
